[package]
name = "halma"
version = "0.1.0"
authors = ["Maximilian Lupke <maxlupke@gmail.com>"]
license = "MIT"

[dependencies]
sdl2 = { version = "0.31", features = ["gfx"] }
rand = "0.4.2"
serde = "1"
serde_derive = "1"
serde_json = "1"

[profile.release]
debug = true
